server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/miresta
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/miresta
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

app:
  cors:
    allowed-origins: "http://localhost:3000,http://localhost:5173"