-- Every time a price setting is edited (amount, label, or confirmed), a row is kept
-- here recording what it changed from/to, who changed it, and when — a proper audit
-- trail for the pricing panel instead of silently overwriting the previous value.
CREATE TABLE price_setting_history (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price_setting_id   BIGINT    NOT NULL REFERENCES price_settings (id),
    previous_amount    BIGINT    NOT NULL,
    new_amount         BIGINT    NOT NULL,
    previous_label     TEXT      NOT NULL,
    new_label          TEXT      NOT NULL,
    previous_confirmed BOOLEAN   NOT NULL,
    new_confirmed      BOOLEAN   NOT NULL,
    changed_by         TEXT,
    changed_at         TIMESTAMP NOT NULL
);
