CREATE TABLE categories (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    code VARCHAR(20)
);

CREATE TABLE products (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              TEXT,
    category_id       BIGINT NOT NULL REFERENCES categories (id),
    acts_as_category  VARCHAR(20)
);

CREATE TABLE product_details (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expiration_date DATE,
    quantity        INTEGER,
    price           BIGINT,
    product_id      BIGINT NOT NULL REFERENCES products (id)
);

INSERT INTO categories (name, code) VALUES
    ('Sopas', 'SOPA'),
    ('Principios', 'PRINCIPIO'),
    ('Proteínas', 'PROTEINA'),
    ('Acompañantes', 'ACOMPANANTE'),
    ('Adicionales', 'ADICIONAL'),
    ('Bebidas', 'BEBIDA'),
    ('Especiales', 'ESPECIAL'),
    ('Envases', 'ENVASE');
