-- Mensajes cortos de sala hacia cocina (ej. "huevo frito", "falta una sopa"). La
-- pantalla de cocina los lee en voz alta por el parlante del PC.
CREATE TABLE kitchen_messages (
    id         BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text       TEXT      NOT NULL,
    sent_by    TEXT      NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_kitchen_messages_created_at ON kitchen_messages (created_at);
