-- Frases de uso rápido que aparecen en "Avisar a cocina" (editables desde Admin).
CREATE TABLE kitchen_phrases (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text       TEXT   NOT NULL,
    sort_order INT    NOT NULL
);

INSERT INTO kitchen_phrases (text, sort_order) VALUES
    ('Falta una sopa', 0),
    ('Falta un jugo', 1),
    ('Huevo frito', 2),
    ('Sin arroz', 3),
    ('Sin ensalada', 4),
    ('Todo sin cebolla', 5),
    ('Un seco (sin sopa)', 6),
    ('Apúrenle una bandeja', 7),
    ('Pedido listo, por favor', 8),
    ('¿Ya va ese pedido?', 9);
