-- Turnos de caja: apertura con base inicial, movimientos de efectivo que no son
-- ventas (entradas/salidas), y cierre con arqueo (esperado vs. contado).
CREATE TABLE cash_shifts (
    id              BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opened_at       TIMESTAMP NOT NULL,
    opened_by       TEXT      NOT NULL,
    opening_cash    BIGINT    NOT NULL,
    closed_at       TIMESTAMP,
    closed_by       TEXT,
    counted_cash    BIGINT,
    expected_cash   BIGINT,
    cash_difference BIGINT,
    notes           TEXT
);

-- Solo puede haber un turno abierto a la vez.
CREATE UNIQUE INDEX idx_cash_shifts_one_open ON cash_shifts ((closed_at IS NULL)) WHERE closed_at IS NULL;

CREATE TABLE cash_movements (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_id   BIGINT      NOT NULL REFERENCES cash_shifts (id),
    type       VARCHAR(10) NOT NULL,
    amount     BIGINT      NOT NULL,
    reason     TEXT        NOT NULL,
    created_at TIMESTAMP   NOT NULL,
    created_by TEXT        NOT NULL
);

CREATE INDEX idx_cash_movements_shift ON cash_movements (shift_id);
