-- Cuadre por método de pago al cerrar un turno — no solo efectivo (que es el único
-- que se cuenta físicamente), también tarjeta/transferencia contra lo que reporte el
-- datáfono/banco, para que el cierre cuadre en su totalidad.
CREATE TABLE cash_shift_method_closings (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_id          BIGINT NOT NULL REFERENCES cash_shifts (id),
    payment_type_name TEXT   NOT NULL,
    expected_amount   BIGINT NOT NULL,
    counted_amount    BIGINT NOT NULL,
    difference_amount BIGINT NOT NULL
);

CREATE INDEX idx_cash_shift_method_closings_shift ON cash_shift_method_closings (shift_id);
