CREATE TABLE menu (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL
);

CREATE TABLE food_type (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

CREATE TABLE menu_offering (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_id      BIGINT NOT NULL REFERENCES menu (id),
    food_type_id BIGINT NOT NULL REFERENCES food_type (id)
);

CREATE TABLE menu_item (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_offering_id  BIGINT NOT NULL REFERENCES menu_offering (id),
    product_id        BIGINT NOT NULL REFERENCES products (id),
    quantity          INTEGER
);

INSERT INTO food_type (name) VALUES
    ('DESAYUNO'),
    ('ALMUERZO'),
    ('ESPECIAL');
