-- Salones (secciones del restaurante) y la posición de cada mesa dentro de su
-- salón, para poder organizar el plano tal como se ve en el local.
CREATE TABLE salons (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL,
    sort_order INT  NOT NULL
);

INSERT INTO salons (name, sort_order) VALUES ('Salón principal', 0);

ALTER TABLE dining_table ADD COLUMN salon_id   BIGINT REFERENCES salons (id);
ALTER TABLE dining_table ADD COLUMN position_x REAL NOT NULL DEFAULT 10;
ALTER TABLE dining_table ADD COLUMN position_y REAL NOT NULL DEFAULT 10;

-- Las mesas que ya existían quedan en el salón principal, acomodadas en una
-- cuadrícula simple (4 por fila) para que no queden todas apiladas — el admin las
-- reacomoda después en Admin -> Salones para que calcen con el plano real.
WITH numbered AS (
    SELECT id, row_number() OVER (ORDER BY number) - 1 AS idx
    FROM dining_table
)
UPDATE dining_table t
SET salon_id   = (SELECT id FROM salons WHERE name = 'Salón principal'),
    position_x = 10 + 20 * (n.idx % 4),
    position_y = 10 + 20 * (n.idx / 4)
FROM numbered n
WHERE n.id = t.id;

ALTER TABLE dining_table ALTER COLUMN salon_id SET NOT NULL;
