-- Un plano guardado por salón (uno solo, se sobreescribe cada vez que se guarda) con
-- la posición de cada mesa en ese momento — para poder "aplicar" y volver a como
-- estaba, si se reacomodó el salón por algo temporal.
CREATE TABLE salon_layouts (
    id       BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id BIGINT    NOT NULL UNIQUE REFERENCES salons (id) ON DELETE CASCADE,
    saved_at TIMESTAMP NOT NULL,
    saved_by TEXT      NOT NULL
);

CREATE TABLE salon_layout_positions (
    id         BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    layout_id  BIGINT NOT NULL REFERENCES salon_layouts (id) ON DELETE CASCADE,
    table_id   BIGINT NOT NULL REFERENCES dining_table (id) ON DELETE CASCADE,
    position_x REAL   NOT NULL,
    position_y REAL   NOT NULL,
    UNIQUE (layout_id, table_id)
);

CREATE INDEX idx_salon_layout_positions_layout ON salon_layout_positions (layout_id);
