CREATE TABLE dining_table_status (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

CREATE TABLE dining_table (
    id        BIGINT PRIMARY KEY,
    number    BIGINT NOT NULL,
    status_id BIGINT NOT NULL REFERENCES dining_table_status (id)
);

INSERT INTO dining_table_status (name) VALUES
    ('OPEN'),
    ('IN_USE');

-- Placeholder tables — adjust to the real dining room layout from the app or here.
INSERT INTO dining_table (id, number, status_id)
SELECT n, n, (SELECT id FROM dining_table_status WHERE name = 'OPEN')
FROM generate_series(1, 6) AS n;
