CREATE TABLE order_status (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE order_type (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

CREATE TABLE payment_type (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

CREATE TABLE customers (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT      NOT NULL,
    phone      TEXT      NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP NOT NULL,
    dining_table_id BIGINT REFERENCES dining_table (id),
    order_status_id BIGINT NOT NULL REFERENCES order_status (id),
    customer_id     BIGINT REFERENCES customers (id),
    payment_type_id BIGINT REFERENCES payment_type (id),
    notes           TEXT,
    subtotal        BIGINT,
    total           BIGINT
);

CREATE TABLE order_items (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT NOT NULL REFERENCES orders (id),
    menu_offering_id BIGINT NOT NULL REFERENCES menu_offering (id),
    order_type_id    BIGINT NOT NULL REFERENCES order_type (id),
    comments         TEXT,
    base_total       BIGINT,
    total            BIGINT,
    togo_surcharge   BIGINT
);

CREATE TABLE order_item_selections (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_id        BIGINT NOT NULL REFERENCES order_items (id),
    product_id           BIGINT NOT NULL REFERENCES products (id),
    quantity             BIGINT NOT NULL,
    unit_extra_price     BIGINT,
    replacement_category VARCHAR(20)
);

INSERT INTO order_status (name) VALUES
    ('PENDING'),
    ('COMPLETED'),
    ('CANCELLED');

INSERT INTO order_type (name) VALUES
    ('IN'),
    ('OUT');

INSERT INTO payment_type (name) VALUES
    ('Efectivo'),
    ('Tarjeta'),
    ('Transferencia');
