CREATE TABLE price_settings (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           VARCHAR(40) NOT NULL UNIQUE,
    label          TEXT        NOT NULL,
    amount_in_situ BIGINT      NOT NULL,
    amount_to_go   BIGINT      NOT NULL,
    confirmed      BOOLEAN     NOT NULL
);

-- amount_to_go carries the actual "para llevar" price where it differs; where the
-- brief says "igual", amount_to_go simply repeats amount_in_situ.
INSERT INTO price_settings (code, label, amount_in_situ, amount_to_go, confirmed) VALUES
    ('DESAYUNO_COMPLETO',            'Desayuno completo (caldo + bandeja)',        8000,  9000,  true),
    ('DESAYUNO_BANDEJA',              'Desayuno solo bandeja (sin caldo)',          7000,  8000,  true),
    ('DESAYUNO_CALDO_SUELTO',         'Desayuno solo caldo (suelto)',                6000,  6000,  false),
    ('DESAYUNO_ACOMPANANTE_ADICION',  'Desayuno adición de acompañamiento',          1000,  1000,  true),
    ('DESAYUNO_PROTEINA_ADICION',     'Desayuno adición de proteína',                4000,  4000,  true),
    ('DESAYUNO_PROTEINA_SUELTA',      'Desayuno proteína sola (suelta)',             4000,  4000,  false),
    ('DESAYUNO_COMPONENTE_SUELTO',    'Desayuno componente suelto',                  1000,  1000,  false),

    ('ALMUERZO_COMPLETO',             'Almuerzo completo (sopa + bandeja)',         10000, 12000,  true),
    ('ALMUERZO_BANDEJA',              'Almuerzo solo bandeja (sin sopa)',            9000, 10000,  true),
    ('ALMUERZO_SOPA_SUELTA',          'Almuerzo solo sopa (suelta)',                 6000,  6000,  false),
    ('ALMUERZO_ACOMPANANTE_ADICION',  'Almuerzo adición de acompañamiento',          1000,  1000,  true),
    ('ALMUERZO_PROTEINA_ADICION',     'Almuerzo adición de proteína',                5000,  5000,  true),
    ('ALMUERZO_PROTEINA_SUELTA',      'Almuerzo proteína sola (suelta)',             4000,  4000,  false),
    ('ALMUERZO_COMPONENTE_SUELTO',    'Almuerzo componente suelto (cualquier acompañante)', 1000, 1000, true),

    ('ESPECIAL_COMPLETO',             'Almuerzo especial (sancocho + bandeja o solo bandeja)', 25000, 25000, true),
    ('ESPECIAL_ACOMPANANTE_ADICION',  'Especial adición de acompañamiento',          1000,  1000,  true),
    ('ESPECIAL_PROTEINA_ADICION',     'Especial adición de proteína',               12000, 12000,  true),
    ('ESPECIAL_COMPONENTE_SUELTO',    'Especial componente suelto (pedido mínimo)',  10000, 10000, false),

    ('BEBIDA_DEFAULT',                'Bebida (precio por defecto)',                 6000,  6000,  false),
    ('BEBIDA_PERSONAL',               'Bebida personal',                             3000,  3000,  false),
    ('BEBIDA_COCA_COLA_1_5',          'Coca-Cola 1.5L',                              7000,  7000,  false);
