CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         TEXT      NOT NULL UNIQUE,
    password_hash TEXT      NOT NULL,
    role          VARCHAR(20) NOT NULL,
    active        BOOLEAN   NOT NULL,
    created_at    TIMESTAMP NOT NULL
);

-- Default admin — email admin@miresta.local / password MirestaAdmin2026!
-- Log in once, then create the real accounts and change this password.
INSERT INTO users (email, password_hash, role, active, created_at) VALUES
    ('admin@miresta.local', '$2b$10$2qeWiUkY6CTwlQbgVat27eA3e3TZs1Y.UAY.gsEZMkMGkaEHAFUvC', 'ADMIN', true, now());
