CREATE TABLE printer_setting (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip   TEXT    NOT NULL,
    port INTEGER NOT NULL
);

-- Placeholder — set the real printer IP from the app once it's on the network.
INSERT INTO printer_setting (ip, port) VALUES ('192.168.1.50', 9100);
