-- Table management (add/remove tables from the app) needs generated ids instead of
-- the manually-assigned ones the seed data used.
ALTER TABLE dining_table ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
    pg_get_serial_sequence('dining_table', 'id'),
    (SELECT COALESCE(MAX(id), 0) FROM dining_table) + 1,
    false
);
